# Site settings
title: J. Nick Enterprises
email: janikgar@pm.me
description: >-
  Jacob Garcia's portfolio of full-stack, front-end, and related web development projects

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://janikgar.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/janikgar
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: lumen

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Chicago
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: projects

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: pages
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
