baseURL = 'https://janikgar.github.io/'
languageCode = 'en-us'
title = 'Jacob Garcia Portfolio'
theme = 'goa'

[Menus]
  main = [
    {Name = "About Jacob", URL = "/posts/about"},
    {Name = "Work History", URL = "/posts/work_history"},
  ]

[params]
  author = "Jacob Garcia"
  authorimage = "headshot.jpg"
  intro = "Specialist in Cloud-Native Engineering and Operations"
  description = "Site Reliability Engineer; previously [Coupa](https://coupa.com) and [Code Willing](https://codewilling.com)"

  [params.meta]
  description = "Jacob Garcia - Site Reliability Engineer"

  [params.social]
  github = "janikgar"
  linkedin = "jacob-garcia-b31483bb"

  [params.extra]
  socialmarkup = true
